packages:
  hon_climate: !include configs/climate/haier_hon.yaml
  turn_on_service: !include configs/api/service.turn_on.yaml
  turn_off_service: !include configs/api/service.turn_off.yaml
  self_cleaning_button: !include configs/button/self_cleaning.yaml
  steri_cleaning_button: !include configs/button/steri_cleaning.yaml
  cleaning_status_text_sensor: !include configs/text_sensor/cleaning_status.yaml
  display_switch: !include configs/switch/display.yaml
  beeper_switch: !include configs/switch/beeper.yaml
  health_mode_switch: !include configs/switch/health_mode.yaml
  quiet_mode_switch: !include configs/switch/quiet_mode.yaml
  restart_switch: !include configs/switch/restart.yaml
  # Vertical airflow direction setting. Works only if the vertical swing is
  # off. You can remove this control if you don't need it
  airflow_vertical_select: !include configs/select/airflow_vertical.yaml
  # Horizontal airflow direction setting. Works only if the horizontal swing
  # is off. You can remove this control if you don't need it
  airflow_horizontal_select: !include configs/select/airflow_horizontal.yaml
  # Additional sensors
  outdoor_temperature_sensor: !include configs/sensor/outdoor_temperature.yaml
  # Make sure that your AC supports humidity before uncommenting it
  # (in the opposite case value will always be 0)
  #indoor_humidity_sensor: !include configs/sensor/humidity.yaml
  # Diagnostic sensors
  indoor_coil_temperature_sensor: !include configs/sensor/indoor_coil_temperature.yaml
  outdoor_coil_temperature_sensor: !include configs/sensor/outdoor_coil_temperature.yaml
  outdoor_defrost_temperature_sensor: !include configs/sensor/outdoor_defrost_temperature.yaml
  outdoor_in_air_temperature_sensor: !include configs/sensor/outdoor_in_air_temperature.yaml
  outdoor_out_air_temperature_sensor: !include configs/sensor/outdoor_out_air_temperature.yaml
  power_sensor: !include configs/sensor/power.yaml
  compressor_frequency_sensor: !include configs/sensor/compressor_frequency.yaml
  compressor_current_sensor: !include configs/sensor/compressor_current.yaml
  expansion_valve_open_degree_sensor: !include configs/sensor/expansion_valve_open_degree.yaml
  # Diagnostic binary sensors
  outdoor_fan_status_binary_sensor: !include configs/binary_sensor/outdoor_fan_status.yaml
  defrost_status_binary_sensor: !include configs/binary_sensor/defrost_status.yaml
  compressor_status_binary_sensor: !include configs/binary_sensor/compressor_status.yaml
  indoor_fan_status_binary_sensor: !include configs/binary_sensor/indoor_fan_status.yaml
  four_way_valve_status_binary_sensor: !include configs/binary_sensor/four_way_valve_status.yaml
  indoor_electric_heating_status_binary_sensor: !include configs/binary_sensor/indoor_electric_heating_status.yaml
  # Diagnostic text sensors
  appliance_name_text_sensor: !include configs/text_sensor/appliance_name.yaml
  protocol_version_text_sensor: !include configs/text_sensor/protocol_version.yaml
