# Build component for different platforms
name: build CI test

on:
  push:
    branches-ignore: [ "doc_test" ]
  pull_request:
    branches: [ "master", "dev" , "experimental" ]

jobs:
  tests:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - esp32-arduino-hon-ethernet.yaml
          - esp32-arduino-hon-wifi.yaml
          - esp32-arduino-smartair2-ethernet.yaml
          - esp32-arduino-smartair2-wifi.yaml
          - esp32-idf-hon-ethernet.yaml
          - esp32-idf-hon-wifi.yaml
          - esp32-idf-smartair2-ethernet.yaml
          - esp32-idf-smartair2-wifi.yaml
          - esp8266-hon-wifi.yaml
          - esp8266-smartair2-wifi.yaml
          - rpipicow-hon-wifi.yaml
          - rpipicow-smartair2-wifi.yaml
          - esp8266-simple-smartair2.yaml
          - esp8266-simple-hon.yaml
          - libretiny-hon.yaml
          - libretiny-smartair2.yaml
          - host-simple-hon.yaml
          - host-simple-smartair2.yaml
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.3
    - name: Install esphome
      run: pip3 install -U esphome
    - name: Version esphome
      run: esphome version
    - name: Install libsodium
      run: sudo apt-get install -y libsodium-dev
    - name: Build ESPHome config
      run: esphome compile tests/${{ matrix.file }}
