# Build component for different platforms
name: build examples

on:
  push:
    branches-ignore: [ "doc_test" ]
  pull_request:
    branches: [ "master", "dev" , "experimental" ]

jobs:
  tests_with_base:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - docs/examples/max-hon.yaml
          - docs/examples/max-smartair2.yaml
          - docs/examples/min-hon.yaml
          - docs/examples/min-smartair2.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3
      - name: Install esphome
        run: pip3 install -U esphome
      - name: Version esphome
        run: esphome version
      - name: Prepering test file
        run: cat docs/examples/.base.yaml ${{ matrix.file }} > ./docs/examples/__test__.yaml
      - name: Preparing secrets.yaml
        run: |
          echo "wifi_ssid: test_ssid" > ./docs/examples/secrets.yaml
          echo "wifi_password: test_pass" >> ./docs/examples/secrets.yaml
      - name: Build ESPHome config
        run: esphome compile ./docs/examples/__test__.yaml
  tests_without_base:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - docs/examples/usb_s3.yaml
          - docs/examples/usb_c3u.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.3
      - name: Install esphome
        run: pip3 install -U esphome
      - name: Version esphome
        run: esphome version
      - name: Preparing secrets.yaml
        run: |
          echo "wifi_ssid: test_ssid" > ./docs/examples/secrets.yaml
          echo "wifi_password: test_pass" >> ./docs/examples/secrets.yaml
      - name: Build ESPHome config
        run: esphome compile ${{ matrix.file }}
